name: trove

dependencies:
  - python=3.7
  - pip
  - jupyter
  - spacy=3.2
  - pyarrow
  - toolz=0.11.1
  - tqdm=4.59.0
  - requests=2.25.1
  - pandas=1.1.5
  - scipy=1.5.2
  - lxml=4.6.2
  - numpy=1.19.2
  - joblib=1.0.1
  - msgpack-python=0.5.6
  - scikit-learn=0.24.1
  - pip:
     - git+https://github.com/chakki-works/seqeval.git